# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IoT',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(help_text='sensor/actuator', max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=50)),
                ('readInterval', models.IntegerField(help_text='seconds')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationModel',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('Method', models.CharField(help_text='Radio/HTTP/HTTPS/etc', max_length=50)),
                ('Address', models.CharField(help_text='IP/Unique address for each action of the IoT device', max_length=100)),
                ('URL', models.CharField(max_length=500)),
                ('RequestType', models.CharField(help_text='GET/POST/etc', max_length=100)),
                ('RequestModel', models.CharField(help_text='GET/POST model', max_length=500)),
                ('IoT_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors_actuators.IoT')),
            ],
        ),
        migrations.CreateModel(
            name='ReadValue',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(help_text='temperature, pressure, humidity,etc', max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('IoT_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors_actuators.IoT')),
            ],
        ),
    ]
